/**
 * POST /api/audit/stream
 *
 * Real-time audit pipeline using Server-Sent Events (SSE).
 *
 * Pipeline: RAG Static Analysis → Red-Team Simulation → Evaluator → Save
 *
 * Request:  { agentName, systemPrompt, tools, repoUrl, filePath }
 * Response: SSE stream (text/event-stream)
 *   - event: status       → { message }
 *   - event: static_result → { score, vulnerabilities }
 *   - event: chat_turn    → { sender, text, compromised? }
 *   - event: final_result → { dynamicScore, overallScore, reportId, ... }
 */
import { NextRequest } from "next/server";
import { analyzeWithRAG } from "@/lib/rag";
import { generateAttack } from "@/lib/llm/attacker";
import { generateAgentResponse } from "@/lib/llm/agent";
import { evaluateTranscript } from "@/lib/llm/evaluator";
import { createClient } from "@/utils/supabase/server";
import type { DetectedAgentTool } from "@/lib/github/types";
import type { Vulnerability, SimulationTurn, GuardrailConfig } from "@/lib/audit/types";

interface SandboxTurn {
  sender: "attacker" | "agent";
  text: string;
  compromised?: boolean;
  targetVulnId?: string;
  targetVulnTitle?: string;
}

interface SandboxResult {
  turns: SandboxTurn[];
  compromisedTurns: number[];
}

// ─── SSE helpers ──────────────────────────────────────────────────

function sseEvent(event: string, data: unknown): string {
  return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
}

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ─── Guardrail generation ─────────────────────────────────────────

function generateGuardrails(
  agentName: string,
  vulnerabilities: Vulnerability[]
): GuardrailConfig[] {
  const hasSecret = vulnerabilities.some((v) =>
    /secret|credential|key|password/i.test(v.title)
  );
  const hasDestructive = vulnerabilities.some((v) =>
    /execution|tool|agency/i.test(v.title)
  );

  return [
    {
      guardrail_type: "llamaguard",
      label: "Llama Guard Rules",
      content: `# Llama Guard Configuration
# Generated by Dobbies for: ${agentName}

${hasSecret ? `[UNSAFE_CATEGORY: S1_CREDENTIAL_DISCLOSURE]
description: "Agent discloses passwords, API keys, or secrets"
trigger_patterns:
  - "password"
  - "secret"
  - "api.*key"
action: BLOCK_RESPONSE\n` : ""}${hasDestructive ? `[UNSAFE_CATEGORY: S2_DESTRUCTIVE_TOOL]
description: "Agent executes destructive operations"
trigger_patterns:
  - "delete"
  - "drop"
  - "remove all"
action: REQUIRE_HUMAN_APPROVAL\n` : ""}[UNSAFE_CATEGORY: S3_PROMPT_INJECTION]
description: "User attempts to override system instructions"
trigger_patterns:
  - "ignore previous instructions"
  - "you are now"
  - "maintenance mode"
action: BLOCK_INPUT`,
    },
    {
      guardrail_type: "regex",
      label: "Regex Output Filters",
      content: `// Regex Guardrail Filters — Dobbies Generated for ${agentName}

const OUTPUT_FILTERS = [
  // Block common secret patterns
  { pattern: /[A-Z_]{6,}_(?:KEY|SECRET|PASS(?:WORD)?|TOKEN)[\\\\w]*/gi, replacement: "[REDACTED:SECRET]" },
  { pattern: /sk-[a-zA-Z0-9]{20,}/g, replacement: "[REDACTED:API_KEY]" },
  { pattern: /Bearer\\s+[a-zA-Z0-9\\-._~+/]+=*/g, replacement: "[REDACTED:TOKEN]" },
  // Block system prompt leakage
  { pattern: /you are an? .{0,80}assistant/gi, replacement: "[REDACTED:SYSTEM_PROMPT]" },
];

export function filterOutput(text: string): string {
  return OUTPUT_FILTERS.reduce(
    (acc, { pattern, replacement }) => acc.replace(pattern, replacement),
    text
  );
}`,
    },
    {
      guardrail_type: "nemo",
      label: "NeMo Guardrails Config",
      content: `# NeMo Guardrails Configuration
# Generated by Dobbies for: ${agentName}

define bot refuse sensitive disclosure
  "I cannot share internal configuration, credentials, or system details."

define flow protect system config
  user ask for configuration
  bot refuse sensitive disclosure

define flow block prompt injection
  user ask to ignore instructions
  bot "I'm not able to override my operating guidelines."${hasDestructive ? `
define flow prevent destructive actions
  user ask to delete or remove
  bot "Destructive operations require explicit approval from an authorized administrator."
` : ""}
rails:
  input:
    flows:
      - block prompt injection
  output:
    flows:
      - protect system config`,
    },
  ];
}

// ─── Supabase save helpers ────────────────────────────────────────

async function ensureAgent(
  supabase: any,
  userId: string,
  agentName: string,
  repoUrl: string | null,
  toolList: DetectedAgentTool[]
): Promise<string | null> {
  const { data: existing } = await supabase
    .from("agents")
    .select("id")
    .eq("user_id", userId)
    .eq("name", agentName)
    .eq("repo_url", repoUrl ?? "")
    .maybeSingle();

  if (existing) return existing.id;

  const { data: inserted } = await supabase
    .from("agents")
    .insert({
      user_id: userId,
      name: agentName,
      repo_url: repoUrl ?? "",
      config: { tools: toolList },
    })
    .select("id")
    .single();

  return inserted?.id ?? null;
}

async function saveVulnerabilities(
  supabase: any,
  reportId: string,
  vulnerabilities: Vulnerability[]
): Promise<{ idMap: Record<string, string>; counts: Record<string, number> }> {
  const idMap: Record<string, string> = {};
  const counts = { vulnerability_count: 0, critical_count: 0, high_count: 0, medium_count: 0, low_count: 0 };

  for (const vuln of vulnerabilities) {
    const { data: inserted } = await supabase
      .from("vulnerabilities")
      .insert({
        report_id: reportId,
        category_id: vuln.category_id,
        title: vuln.title,
        severity: vuln.severity,
        description: vuln.description,
        remediation: vuln.remediation,
        file_path: vuln.file_path ?? null,
        line_number: vuln.line_number ?? null,
        code_snippet: vuln.code_snippet ?? null,
        root_cause: vuln.root_cause ?? null,
        attack_path: vuln.attack_path ?? null,
        impact: vuln.impact ?? null,
        cvss_score: vuln.cvss_score ?? null,
        status: vuln.status ?? "open",
      })
      .select("id")
      .single();

    if (inserted) {
      idMap[vuln.id] = inserted.id;
    }
    counts.vulnerability_count++;
    if (vuln.severity === "critical") counts.critical_count++;
    else if (vuln.severity === "high") counts.high_count++;
    else if (vuln.severity === "medium") counts.medium_count++;
    else if (vuln.severity === "low") counts.low_count++;
  }

  return { idMap, counts };
}

async function saveSimulationTurns(
  supabase: any,
  reportId: string,
  turns: SimulationTurn[],
  vulnIdMap: Record<string, string>
): Promise<number> {
  let compromisedCount = 0;
  for (const turn of turns) {
    // Map old vuln ID to new UUID if present
    const mappedVulnId = turn.target_vuln_id ? (vulnIdMap[turn.target_vuln_id] ?? null) : null;
    if (turn.compromised) compromisedCount++;

    await supabase.from("simulation_turns").insert({
      report_id: reportId,
      turn_number: turn.turn_number,
      sender: turn.sender,
      text: turn.text,
      target_vuln_id: mappedVulnId,
      compromised: turn.compromised ?? false,
    });
  }
  return compromisedCount;
}

async function saveGuardrails(
  supabase: any,
  reportId: string,
  guardrails: GuardrailConfig[]
): Promise<void> {
  for (const g of guardrails) {
    await supabase.from("guardrails").insert({
      report_id: reportId,
      guardrail_type: g.guardrail_type,
      label: g.label,
      content: g.content,
    });
  }
}

// ─── Route handler ────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    if (!process.env.OPENAI_API_KEY) {
      return new Response(
        sseEvent("error", { message: "OPENAI_API_KEY is not configured. AI vs AI auditing requires an active OpenAI API key." }),
        { status: 400, headers: { "Content-Type": "text/event-stream" } }
      );
    }

    const { agentName, systemPrompt, tools, repoUrl, filePath, content } = await request.json();

    // Use content as fallback if systemPrompt is empty
    const prompt = systemPrompt || content || "";

    if (!agentName) {
      return new Response(
        sseEvent("error", { message: "agentName is required" }),
        { status: 400, headers: { "Content-Type": "text/event-stream" } }
      );
    }

    const toolList: DetectedAgentTool[] = tools ?? [];
    const toolNames = toolList.map((t: DetectedAgentTool) => t.name);
    const toolsDescription = toolList
      .map((t: DetectedAgentTool) => `${t.name}: ${t.description}`)
      .join("\n");

    // ── Streaming response ───────────────────────────────────────
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        try {
          // ── PHASE 1: RAG Static Analysis ──────────────────────
          controller.enqueue(encoder.encode(
            sseEvent("status", { message: `Initializing audit pipeline for "${agentName}"...` })
          ));
          await delay(300);

          controller.enqueue(encoder.encode(
            sseEvent("status", { message: `Analyzing agent architecture for "${agentName}"...` })
          ));
          await delay(300);

          controller.enqueue(encoder.encode(
            sseEvent("status", { message: `Scanning ${toolNames.length} tool definition${toolNames.length !== 1 ? "s" : ""} for dangerous operations...` })
          ));
          await delay(300);

          controller.enqueue(encoder.encode(
            sseEvent("status", { message: "Performing LLM-based semantic analysis of system prompt..." })
          ));
          await delay(400);

          // Run LLM-based static analysis (async)
          const ragResult = await analyzeWithRAG(prompt, toolsDescription, toolList);
          const staticScore = ragResult.score;
          const vulnerabilities = ragResult.vulnerabilities;

          controller.enqueue(encoder.encode(
            sseEvent("static_result", {
              score: staticScore,
              vulnerabilities,
              message: `Static analysis complete — ${vulnerabilities.length} vulnerabilities detected`,
            })
          ));

          // ── PHASE 2: Red-Team Simulation ──────────────────────
          controller.enqueue(encoder.encode(
            sseEvent("status", { message: "Starting automated red-teaming simulation..." })
          ));
          await delay(400);

          controller.enqueue(encoder.encode(
            sseEvent("status", { message: "Attacker LLM initialized — probing with adversarial prompts..." })
          ));
          await delay(300);

          // Variables to track simulation state
          let sandboxResult: SandboxResult;
          const fullTranscript: SandboxTurn[] = [];

          // ── LLM-Powered Attacker ──
          // Each turn: LLM generates attacker prompt → LLM simulates agent response
          // Dynamic turns: 1 attack per vulnerability, min 2, max 10
          const numTurns = Math.max(2, Math.min(vulnerabilities.length, 10));

          for (let turnNum = 0; turnNum < numTurns; turnNum++) {
            // Generate attacker prompt via LLM — target 1 vulnerability per turn
            const targetVuln = turnNum < vulnerabilities.length
              ? vulnerabilities[turnNum]
              : vulnerabilities[vulnerabilities.length - 1]; // fallback: repeat last vuln
            const attackerMsg = await generateAttack(
              prompt,
              toolList,
              fullTranscript,
              vulnerabilities,
              targetVuln,
            );

            if (!attackerMsg) {
              throw new Error("Attacker LLM failed to generate attack — aborting simulation");
            }
            const attackText = attackerMsg;

            // Stream attacker message
            await delay(500);
            controller.enqueue(encoder.encode(
              sseEvent("chat_turn", {
                sender: "attacker",
                text: attackText,
                targetVulnId: targetVuln?.id,
                targetVulnTitle: targetVuln?.title,
              })
            ));
            fullTranscript.push({
              sender: "attacker",
              text: attackText,
              targetVulnId: targetVuln?.id,
              targetVulnTitle: targetVuln?.title,
            });

            // Simulate agent response using Agent LLM
            const agentText = await generateAgentResponse(prompt, toolList, fullTranscript);
            if (!agentText) {
              throw new Error("Agent LLM failed to generate response — aborting simulation");
            }
            // Compromise flag will be determined by evaluator LLM at Phase 3
            const isCompromised = false;

            // Stream agent response
            await delay(800);
            controller.enqueue(encoder.encode(
              sseEvent("chat_turn", {
                sender: "agent",
                text: agentText,
                compromised: isCompromised,
              })
            ));
            fullTranscript.push({
              sender: "agent",
              text: agentText,
              compromised: isCompromised,
            });
          }

          sandboxResult = {
            turns: fullTranscript,
            compromisedTurns: [],
          };

          // ── PHASE 3: Scorer & Guardrails ──────────────────────
          await delay(300);
          controller.enqueue(encoder.encode(
            sseEvent("status", { message: "Running AI Security Evaluator on transcript..." })
          ));

          let dynamicScore: number;
          let evaluationRisks: string[] = [];
          let evaluationRecommendations: string[] = [];

          // LLM-Powered Evaluator for nuanced scoring
          const evalResult = await evaluateTranscript(
            agentName,
            prompt,
            sandboxResult.turns,
          );
          if (!evalResult) {
            throw new Error("Evaluator LLM failed to analyze transcript — aborting scoring");
          }
          dynamicScore = evalResult.dynamicScore;
          evaluationRisks = evalResult.risks;
          evaluationRecommendations = evalResult.recommendations;

          // Apply compromised turns from evaluator LLM
          const evaluatorCompromised: number[] = [];
          if (evalResult.compromisedTurns.length > 0) {
            for (const turnNum of evalResult.compromisedTurns) {
              const transcriptIdx = turnNum - 1; // 1-based → 0-based
              if (transcriptIdx >= 0 && transcriptIdx < fullTranscript.length) {
                fullTranscript[transcriptIdx].compromised = true;
                evaluatorCompromised.push(Math.ceil((transcriptIdx + 1) / 2)); // Convert to round number
              }
            }
          }

          if (evaluatorCompromised.length > 0) {
            controller.enqueue(encoder.encode(
              sseEvent("status", {
                message: `⚠ Agent compromised on turn(s) ${evaluatorCompromised.join(", ")}`,
              })
            ));
          }
          const overallScore = Math.round((staticScore + dynamicScore) / 2);

          // ── Combine vulnerabilities ──
          const allVulnerabilities = vulnerabilities;

          const guardrails = generateGuardrails(agentName, allVulnerabilities);

          const simulationLogs: SimulationTurn[] = sandboxResult.turns.map((turn, i) => ({
            id: `turn-${i}`,
            turn_number: i + 1,
            sender: turn.sender,
            text: turn.text,
            compromised: turn.compromised ?? false,
            target_vuln_id: turn.targetVulnId ?? null,
          }));

          const reportId = `audit-${Date.now()}`;

          // ── Save to Supabase (normalized tables) ──────────────
          try {
            const supabase = await createClient();
            const { data: { session } } = await supabase.auth.getSession();

            if (session?.user) {
              // 1. Ensure agent record exists
              const agentId = await ensureAgent(supabase, session.user.id, agentName, repoUrl ?? null, toolList);

              // 2. Insert audit report
              await supabase.from("audit_reports").insert({
                id: reportId,
                user_id: session.user.id,
                agent_id: agentId,
                agent_name: agentName,
                repo_url: repoUrl ?? null,
                file_path: filePath ?? null,
                system_prompt: prompt,
                tools_json: JSON.stringify(toolList),
                static_score: staticScore,
                dynamic_score: dynamicScore,
                overall_score: overallScore,
                status: "completed",
              });

              // 3. Save vulnerabilities + get ID mapping + counts
              const { idMap, counts } = await saveVulnerabilities(supabase, reportId, allVulnerabilities);

              // 4. Save simulation turns
              const compromisedCount = await saveSimulationTurns(supabase, reportId, simulationLogs, idMap);

              // 5. Save guardrails
              await saveGuardrails(supabase, reportId, guardrails);

              // 6. Update denormalized counts on the report
              await supabase
                .from("audit_reports")
                .update({
                  vulnerability_count: counts.vulnerability_count,
                  critical_count: counts.critical_count,
                  high_count: counts.high_count,
                  medium_count: counts.medium_count,
                  low_count: counts.low_count,
                  compromised_count: compromisedCount,
                })
                .eq("id", reportId);
            }
          } catch {
            // No Supabase configured — skip saving
          }

          // ── Final result ──────────────────────────────────────
          controller.enqueue(encoder.encode(
            sseEvent("final_result", {
              reportId,
              agentName,
              staticScore,
              dynamicScore,
              overallScore,
              vulnerabilities: allVulnerabilities,
              simulationLogs,
              guardrails,
            })
          ));

          controller.close();
        } catch (err) {
          const message = err instanceof Error ? err.message : "Pipeline error";
          controller.enqueue(encoder.encode(sseEvent("error", { message })));
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Invalid request";
    return new Response(
      sseEvent("error", { message }),
      { status: 400, headers: { "Content-Type": "text/event-stream" } }
    );
  }
}
