-- Migration: Create audit_reports table
-- Description: Stores audit reports generated by Dobbies

-- Create audit_reports table
CREATE TABLE IF NOT EXISTS public.audit_reports (
  id            TEXT PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  agent_name    TEXT NOT NULL,
  repo_url      TEXT,
  file_path     TEXT,
  system_prompt TEXT NOT NULL,
  tools_json    JSONB DEFAULT '[]'::jsonb,
  static_score  INTEGER DEFAULT 0,
  dynamic_score INTEGER DEFAULT 0,
  overall_score INTEGER DEFAULT 0,
  vulnerabilities JSONB DEFAULT '[]'::jsonb,
  simulation_logs JSONB DEFAULT '[]'::jsonb,
  guardrails    JSONB DEFAULT '[]'::jsonb,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.audit_reports ENABLE ROW LEVEL SECURITY;

-- Policies

-- Users can SELECT only their own reports
CREATE POLICY "Users can view own reports"
  ON public.audit_reports
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can INSERT their own reports
CREATE POLICY "Users can insert own reports"
  ON public.audit_reports
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can UPDATE only their own reports
CREATE POLICY "Users can update own reports"
  ON public.audit_reports
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can DELETE only their own reports
CREATE POLICY "Users can delete own reports"
  ON public.audit_reports
  FOR DELETE
  USING (auth.uid() = user_id);

-- Index on user_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_audit_reports_user_id
  ON public.audit_reports(user_id);

-- Index on created_at for sorting
CREATE INDEX IF NOT EXISTS idx_audit_reports_created_at
  ON public.audit_reports(created_at DESC);
